# Arrays

In [4]:
import numpy

def arrays(arr):
    return(numpy.array(arr[::-1],float))

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


# Shape Reshape

In [2]:
print(numpy.array(input().split(),int).reshape(3,3))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Transpose and Flatten

In [3]:
x, y = map(int, input().split())
array = numpy.array([input().strip().split() for _ in range(y)], int)
print (array.transpose())
print (array.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


# Concatenate

In [9]:
m, n, p = map(int,input().split())
arrM = numpy.array([input().split() for _ in range(m)],int)
arrN = numpy.array([input().split() for _ in range(n)],int)
print(numpy.concatenate((arrM, arrN), axis = 0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


# Zeros and Ones

In [2]:
N = tuple(map(int,input().strip().split()))
print(numpy.zeros(N, dtype=numpy.int))
print(numpy.ones(N, dtype=numpy.int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


# Eye and Identity

In [4]:
a, b = map(int, input().split())
numpy.set_printoptions(legacy='1.13')
print(numpy.eye(a,b))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


# Array Mathematics

In [5]:
n , m = map(int,input().split())
a , b = (numpy.array([input().split() for _ in range(n)],int) for _ in range(2))
print(a+b, a-b, a*b, a//b, a%b, a**b, sep='\n')

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


# Floor Ceil and Rint

In [6]:
numpy.set_printoptions(legacy='1.13')
nums = numpy.array(input().split(' '),float)
print(numpy.floor(nums))
print(numpy.ceil(nums))
print(numpy.rint(nums))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


# Sum and Prod

In [7]:
x , y = map(int,input().split())
array1 = numpy.array([input().split() for _ in range(x)], int)
print(numpy.prod((numpy.sum(array1,axis=0))))

2 2
1 2
3 4
24


# Min and Max

In [2]:
import numpy
x, y = map(int,input().split())
array = numpy.array([input().strip().split() for _ in range(y)], int)
print(numpy.max(numpy.min(array, axis = 1), axis = None))

4 2
2 5
3 7
3


# Mean, Var and Std

In [3]:
x, y = map(int, input().split())
array = numpy.array([input().split() for _ in range(x)], int)
numpy.set_printoptions(sign=' ')
print(numpy.mean(array,axis=1))
print(numpy.var(array,axis=0))
print(numpy.std(array,None))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.118033988749895


# Dot and Cross

In [4]:
x=int(input())
array1 = numpy.array([input().split() for _ in range(x)], int)
array2 = numpy.array([input().split() for _ in range(x)], int)
print(numpy.dot(array1,array2))

2
1 2
3 4 
1 2
3 4
[[ 7 10]
 [15 22]]


# Inner and Outer 

In [6]:
array1 = numpy.array(input().split(), int)
array2 = numpy.array(input().split(), int)
print(numpy.inner(array1,array2))
print(numpy.outer(array1,array2))

0 1
2 3
3
[[0 0]
 [2 3]]


# Polynomials

In [7]:
import numpy
x = list(map(float,input().split()))
y = input()
print(numpy.polyval(x,int(y)))

1.1 2 3
0
3.0


# Linear Algebra 

In [8]:
x = int(input())
array1 = numpy.array([input().split() for _ in range(x)],float)
numpy.set_printoptions(legacy='1.13')
print(numpy.linalg.det(array1))

2
1.1 1.1
1.1 1.1
0.0
